name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    env:
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_TAG
          script: |
            cd ~/Docker_Projects/devboard-starter
            git pull origin main
            export IMAGE_TAG=$IMAGE_TAG
            docker compose pull
            docker compose up -d
            docker image prune -f



