# Goal: To scan the dependencies / libraries installed
name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      
      - name: install dependencies
        run: npm ci
      
      - uses: oke-py/npm-audit-action@v5
