# Goal: Implement shift left, i.e., DevSecOps end-to-end for this project.

name: DevSecOps

on: 
  push:

jobs:

  # Secrets Scan
  secret_scan:
      uses: ./.github/workflows/secret_scanning.yml
      secrets: inherit
  # Code
  code:
      needs: secret_scan
      uses: ./.github/workflows/lint.yml

  # SAST
  sast:
    needs: code
    uses: ./.github/workflows/sonar_scan.yml
    secrets: inherit

  # Dependency Scan
  dependency_scan:
    needs: sast
    uses: ./.github/workflows/dependency_scan.yml
    
  #Build
#  build-and-push:
      # secrets: inherit
      # needs: code
      # uses: ./.github/workflows/ci.yml

  # Test
  # deploy:
  #     secrets: inherit
  #     needs: build-and-push
  #     uses: ./.github/workflows/cd.yml



